### ISSUE TITLE
bug: old users not able to login

### ISSUE THREAD

**Issue by sarvalabs-gokul** [sarvalabs/iome-react-widget#5]
**Describe the bug**
Login is failing for old users. At the same time, new users are able to login. While investigating the issue we found out that the authorization API call is throwing 500 (Internal Server Error).

**Steps to reproduce the behavior**
1. Go to [voyage-dev](https://app-voyage.moibit.io/)
2. Click on the login button on the top right of the navbar.
3. Click on the Login with iome button.
4. Error is not being shown.

**Expected behavior**
Expecting all the existing users to be able to login.

**Screenshots**
![Screenshot 2023-11-10 at 5 25 48 PM](https://github.com/sarvalabs/iome-react-widget/assets/118281049/f0597ad4-1fcf-4ccd-b876-94c1cce5d629)
![Screenshot 2023-11-10 at 5 31 25 PM](https://github.com/sarvalabs/iome-react-widget/assets/118281049/505b5087-d044-4e18-94a6-5e3a87cd5a6b)

**Comment by sarvalabs-rahul** [comment]
@sarvalabs-sai Any update on this ?
